apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Postgres
    uid: postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: shopiscan
    secureJsonData:
      password: shopiscan
    jsonData:
      database: shopiscan
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
